@echo off
echo Starting AI Duplicate Detection Service (Prototype)...
start "AI Duplicate Detection Backend" cmd /k "cd /d E:\Users\ai-duplicate-detection\Alpha && .venv\Scripts\python.exe -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
echo Service is launching...
echo Swagger UI Docs: http://localhost:8000/docs
